# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('title', models.CharField(max_length=75, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('author', models.CharField(max_length=40, verbose_name='Author')),
            ],
        ),
    ]
